version: "3.8"

services:
  # 1. データベースサービス
  db:
    image: postgres:16-alpine
    container_name: memo-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # .envから読み込み
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # .envから読み込み
      POSTGRES_DB: ${POSTGRES_DB} # .envから読み込み
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  # 2. バックエンドサービス
  backend:
    build:
      context: ./backend
    container_name: memo-backend
    volumes:
      - ./backend:/app
    ports:
      - "${PORT}:${PORT}"
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL} # Prismaはこれを使う
      PORT: ${PORT}
    depends_on:
      - db
    command: npx ts-node index.ts

  # 3. フロントエンドサービス
  frontend:
    build:
      context: ./frontend
    container_name: memo-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
